### ISSUE TITLE
Missing coding standards

### ISSUE THREAD

**Issue by bambuchaAdm** [HackerspaceKRK/improved-eureka#1]
uC part use com uncommon code-style (mixing snake_case with CamelCase) it would be nice to get unified it or provide little code style guide in repository README

**Comment by Teeed** [comment]
Code follows STM32CubeMX and STM32HAL Libraries code conventions.

**Comment by bambuchaAdm** [comment]
ok, add it information to README.

Add please add link to it.

**Comment by Teeed** [comment]
Fixed
